alias workspace="cd ${GITPOD_REPO_ROOT}"
alias webui="gp preview $(gp url 8080)"
alias ex1="cd ${GITPOD_REPO_ROOT}/exercises/async-activity-completion/practice"
alias ex2="cd ${GITPOD_REPO_ROOT}/exercises/querying-workflows/practice"
alias ex3="cd ${GITPOD_REPO_ROOT}/exercises/sending-signals-client/practice"
alias ex4="cd ${GITPOD_REPO_ROOT}/exercises/sending-signals-external/practice"
alias ex5="cd ${GITPOD_REPO_ROOT}/samples/custom-search-attributes"
alias ex1s="cd ${GITPOD_REPO_ROOT}/exercises/async-activity-completion/solution"
alias ex2s="cd ${GITPOD_REPO_ROOT}/exercises/querying-workflows/solution"
alias ex3s="cd ${GITPOD_REPO_ROOT}/exercises/sending-signals-client/solution"
alias ex5s="cd ${GITPOD_REPO_ROOT}/exercises/sending-signals-external/solution"
echo "Your workspace is located at: ${GITPOD_REPO_ROOT}"
echo "Type the command     workspace      to return to the workspace directory at any time."
